---
server: "caduceator-instance-123.example.com"

########################################
#   Labeling/Tracing via HTTP Headers Configuration
########################################
build:
region:
flavor:

########################################
#   Primary Endpoint Configuration
########################################
primary:
  address: ":5000"

########################################
#   Health Endpoint Configuration
########################################

health:
  port: ":5001"
  endpoint: "/health"

########################################
#   Debugging/Pprof Configuration
########################################
pprof:
  address: ":5002"

########################################
#   Metrics Configuration
########################################
metric:
  address: ":5003"
  metricsOptions:
    namespace: xmidt
    subsystem: caduceator

########################################
#   Logging Related Configuration
########################################

log:
  file: "stdout"
  level: "DEBUG"
  maxsize: 50
  maxage: 30
  maxbackups: 10
  json: true

########################################
#   Vegeta Related Configuration
########################################
# vegetaConfig:
#   frequency: 1000
#   period: "5s"
#   connections: 500
#   duration: 0
#   maxRoutines: 0
#   postURL: "http://caduceus:6000/api/v3/notify"
#   sleepTime: "5s"
#   clientTimeout: "5s"
#   messages:
#     fixedCurrentTime: false
#     messageContents:
#       - wrp:
#           source: "mac:112233445566"
#           destination: "event:device-status/mac:112233445566/offline"
#           metadata:
#             - "some-key": "some-value"
#             - "another key": "another value"
#           transactionUUID: "uuid-string"
#         payload:
#           - "payloadKey": "payloadVal"
#         bootTimeOffset: "-2h"
#         birthdateOffset: "-1h"
#   vegetaRehash:
#     routines: 0
#     period: "1s"
#     frequency: 500
#     connections: 500
#     duration: 0
#     messages:
#       fixedCurrentTime: false
#       messageContents:
#         - wrp:
#             source: "mac:112233445566"
#             destination: "event:device-status/mac:112233445566/offline"
#             metadata:
#               - "some-key": "some-value"
#               - "another key": "another value"
#             transactionUUID: "uuid-string"
#           payload:
#             - "payloadKey": "payloadVal"
#           bootTimeOffset: "-2h"
#           birthdateOffset: "-1h"

# The following is an example Caduceator vegeta configuration to load test Caduceus
# of a slow consumer by sending 1000 events per second and only wanting Caduceator
# to be cutoff by Caduceus 5 times.

vegetaConfig:
  frequency: 1000
  period: "1s"
  connections: 500
  duration: 0
  maxRoutines: 5
  sleepTime: "45s"
  clientTimeout: "5s"
  postURL: "http://caduceus:6000/api/v3/notify"
  messages:
    fixedCurrentTime: false
    messageContents:
      - wrp:
          source: "mac:112233445566"
          destination: "event:device-status/mac:112233445566/offline"
          metadata:
            - "some-key": "some-value"
            - "another key": "another value"
          transactionUUID: "uuid-string"
        payload:
          - "payloadKey": "payloadVal"
        bootTimeOffset: "-2h"
        birthdateOffset: "-1h"

# By adding the following rehash configuration to vegetaConfig,
# it will simulate a 2 rehash events in Caduceus by sending an additional 500 events
# a second every 10 minutes. If routine is set to 0 then no rehash event will occur in Caduceus.

# vegetaConfig:
#   frequency: 1000
#   period: "1s"
#   connections: 500
#   duration: 0
#   maxRoutines: 5
#   sleepTime: "45s"
#   clientTimeout: "5s"
#   postURL: "http://caduceus:6000/api/v3/notify"
#   messages:
#     fixedCurrentTime: false
#     messageContents:
#       - wrp:
#           source: "mac:112233445566"
#           destination: "event:device-status/mac:112233445566/offline"
#           metadata:
#             - "some-key": "some-value"
#             - "another key": "another value"
#           transactionUUID: "uuid-string"
#         payload:
#           - "payloadKey": "payloadVal"
#         bootTimeOffset: "-2h"
#         birthdateOffset: "-1h"
#   vegetaRehash:
#     routines: 2
#     frequency: 500
#     period: "1s"
#     connections: 500
#     duration: 0
#     messages:
#       fixedCurrentTime: false
#       messageContents:
#         - wrp:
#             source: "mac:112233445566"
#             destination: "event:device-status/mac:112233445566/offline"
#             metadata:
#               - "some-key": "some-value"
#               - "another key": "another value"
#             transactionUUID: "uuid-string"
#           payload:
#             - "payloadKey": "payloadVal"
#           bootTimeOffset: "-2h"
#           birthdateOffset: "-1h"

########################################
#   Prometheus Related Configuration
########################################
prometheusConfig:
  queryURL: "http://prometheus:9090/api/v1/query"
  queryExpression: "sum(xmidt_caduceus_outgoing_queue_depths) by (url)"
  metricsURL: "http://caduceator:5000/events"
  auth: ""
  timeout:

########################################
#   Authorization Related Configuration
########################################
secret:
  header: "X-Webpa-Signature"
  delimiter: "="

########################################
#   Webhook Registration Related Configuration
########################################
webhook:
  registrationInterval: "3m"
  timeout: "5s"
  registrationURL: "http://caduceus:6000/hook"
  webhookCount: 1
  request:
    webhookConfig:
      url: "http://caduceator:5000/events"
      failureURL: "http://caduceator:5000/cutoff"
      secret: "secret1234"
      maxRetryCount: 1
    events: "device-status.*"
  basic: "Basic dXNlcjpwYXNz"
